### PR TITLE
format bash commands

### PR DESCRIPTION
**Pull request by siansiansu**
Hi,

I just found that there are two mixed style of the loop in the code block.

Some doesn't contain an additional blank
```bash
for i in $(ls); do echo file $i;done
```

and some contains an additional blank

```bash
for i in *; do echo file $i; done
```

I just format this doc to make it more consistent.

Please help to review this minimal change, thanks 😀

Best Regards,

Alex

### CODE REVIEW

**Comment by onceupon** [comment]
i should fix the consistency for `done`; but for the double spaces at the end of some lines, i added them intentionally for markdown to add a next line to it, otherwise the content will be displayed in one line.

**Comment by siansiansu** [comment]
Apologize for the misunderstanding.

I just updated this minimal change.
Please let me know If there is any problem 🙂

**Review by onceupon — APPROVED** [review]
nice, thanks for the effort

**Comment by mu578** [comment]
you might have issues with wildcard selector if files contain space, usually better learning a bit of awk scripting , regexp, filtering for file system manipulation, it may save you a lot of time and headaches.

**Pull request merged**
